export const STORE_CAMPAIGN_DATA = 'STORE_CAMPAIGN_DATA';
export const SET_SEARCH_KEY = 'SET_SEARCH_KEY';
export const SET_DATE_RANGE = 'SET_DATE_RANGE';
export const SET_SNACKBAR_DISPLAY = 'SET_SNACKBAR_DISPLAY';
export const SET_MODALPOPUP_DISPLAY = 'SET_MODALPOPUP_DISPLAY';
